spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: 12345

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  issuer: vvwv3092@gmail.com
  secret_key: tlsgmltjd-s